<?php

namespace BauobjektBundle\Repository;

/**
 * AnfrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnfrageRepository extends \Doctrine\ORM\EntityRepository
{
}
